remotehat/hat/urls.py
from django.urls import path

from . import views

app_name = 'hat'
urlpatterns = [
    path('', views.index, name='index'),
    path('add_name', views.add_name, name='add_name'),
    path('play', views.play, name='play'),
    path('retrieve_name', views.retrieve_random_name, name='retrieve_random_name'),
    path('submit_name', views.submit_name, name='submit_name'),
]

remotehat/remotehat/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('hat.urls')),
    path('admin/', admin.site.urls),
]

remotehat/hat/models.py
from django.db import models


class FamousNames(models.Model):
    name_text = models.CharField(max_length=200)
    round_number = models.IntegerField(default=1)

class Rounds(models.Model):
    current_round = models.IntegerField(default=1)

remotehat/hat/views.py
from django.shortcuts import render
import random

from .models import FamousNames, Rounds

def index(request):
    return render(request, 'hat/index.html')

def add_name(request):
    return render(request, "hat/add_name.html")

def play(request):
    return render(request, "hat/play.html")

def submit_name(request):
    try:
        famous_name = request.POST['famous_name']
        if famous_name:
            f = FamousNames(name_text=famous_name)
            f.save()
    except:
        # Not sure what error might be raised here
        return render(request, 'hat/add_name.html', {
            'error_message': "An error occurred",
        })
    return render(request, 'hat/submit_name.html', {'famous_name': famous_name})

def retrieve_random_name(request):
    current_round = Rounds.objects.get()
    guessed_name = request.POST.get("famous_name")
    if guessed_name:
        successful_guess = FamousNames.objects.filter(round_number=current_round.current_round, name_text = guessed_name)[0]
        successful_guess.round_number += 1
        successful_guess.save()

    if not FamousNames.objects.filter(round_number=current_round.current_round):
        famous_name = "No names left in hat! End of round {}".format(current_round.current_round)
        current_round.current_round +=1
        current_round.save()
        ## Note that the 'got it, next' button still appears and will make this all fall over
       ## So need to make it not fall over
    else:
        names_in_round = list(FamousNames.objects.filter(round_number=current_round.current_round))
        famous_name = random.choice(names_in_round).name_text
    return render(request, 'hat/retrieve_name.html', {'famous_name': famous_name})

remotehat/hat/templates/hat/add_name.html
<html>
{% include "hat/header.html" %}
  <body>
    <h1>Add Name</h1>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'hat:submit_name' %}" method="post">
    {% csrf_token %}
      <input type="text" name="famous_name" id="famous_name">
      <label for="famous_name">Enter famous name</label><br>
      <input type="submit" value="Enter">
    </form>
  </body>
</html>

remotehat/hat/templates/hat/add_names.html
<h1>Add Name</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'hat:submit_name' %}" method="post">
{% csrf_token %}
<input type="text" name="famous_name" id="famous_name">
<label for="famous_name">Enter famous name</label><br>
<input type="submit" value="Enter">
</form>

remotehat/hat/templates/hat/header.html
<head>
  <title>Hat!</title>
  <meta name="viewport" content="initial-scale=1, shrink-to-fit=no">
</head>

remotehat/hat/templates/hat/index.html
<html>
{% include "hat/header.html" %}
  <body>
    <h1>Hat!</h1>

    <ul>
      <li><a href="{% url 'hat:add_name' %}">Add names</a></li>
      <li><a href="{% url 'hat:play' %}">Play</a></li>
    </ul>
  </body>
</html>

remotehat/hat/templates/hat/play.html
<html>
{% include "hat/header.html" %}
  <body>
    <h1>Play Hat!</h1>

    <a href="{% url 'hat:retrieve_random_name' %}">Start turn</a>
  </body>
</html>

remotehat/hat/templates/hat/retrieve_name.html
<html>
{% include "hat/header.html" %}
  <body>
    <h1>{{ famous_name }}</h1>

    <form action="{% url 'hat:retrieve_random_name' %}" method="post">
    {% csrf_token %}
      <input type="hidden" id="famous_name" name="famous_name" value="{{ famous_name }}">
      <input type="submit" value="Got it! Next!">
    </form>

    <a href="{% url 'hat:play' %}">End turn</a>
  </body>
</html>

remotehat/hat/templates/hat/submit_name.html
<html>
{% include "hat/header.html" %}
  <body>
    <h1>You've submitted: {{ famous_name }}</h1>

    <form action="{% url 'hat:add_name' %}" method="post">
    {% csrf_token %}
      <input type="submit" value="Add another">
    </form>

    <a href="{% url 'hat:play' %}">Finished, I want to play now</a>
  </body>
</html>